language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
  - npm run test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./
  on:
    branch: master