const singleWordHelper = Object.freeze({
    issue: 'issue',
    id: 'ID',
    looks: 'looks',
    like: 'like',
    resolved: 'resolved',
    date: 'date',
    saved: 'saved',
    search: 'search',
    vcs: 'vcs',
    changes: 'changes',
    visible: 'visible',
    to: 'to',
    depends: 'Depends',
    on: 'on',
    is: 'Is',
    duplicated: 'duplicated',
    by: 'by',
    required: 'required',
    for: 'for',
    relates: 'Relates',
    subtask: 'Subtask',
    of: 'of',
    sort: 'sort',
    work: 'work',
    author: 'author',
    type: 'type',
    affected: 'Affected',
    versions: 'versions',
    fix: 'Fix',
    fixed: 'Fixed',
    in: 'in',
    build: 'build',
});

module.exports = singleWordHelper;